import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header/header";
import HeroSection from "./components/HeroSection/heroSection";
import AboutPage from "./components/About/about";
import ContactPage from "./components/Contact/contact";
import Footer from "./components/Footer/footer";
import Project from "./components/Project/project";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <section>
          <Header/>
        </section> 

      <section className="my-4">
      <HeroSection/>
      </section>

      <section className="my-4">
      <AboutPage/>
      </section>

      <section className="my=4">
      <Project/>
      </section> 


      <section className="my-4">
      <ContactPage/>
      </section>
      <Footer/>
        {/* {children} */}
      </body>
    </html>
  );
}
